### ISSUE TITLE
Rails 4 in Action

### ISSUE THREAD

**Issue by aunmro** [aunmro/notes#8]
http://book.douban.com/subject/24318447/

**Comment by aunmro** [comment]
#### 安装 Rspec 和 capybara

1. 安装 gem

```ruby
group :development, :test do
  gem 'rspec-rails'
end

group :test do
  gem 'capybara'
end
```

2. `rails g rspec:install`

#### 数据库配置

生产环境和开发环境使用同一种数据库

config/database.yml 文件

**pg 配置例子**

```yaml
development:
  adapter: postgresql
  database: ticketee_development
  username: root
  password: t0ps3cr3t
```

**使用mysql，encoding 设置为 utf-8**

```yaml
development:
  adapter: mysql2
  database: ticketee_development
  username: root
  password: t0ps3cr3t
  encoding: utf8
```
